apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.6.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      path.repo: ["/usr/share/elasticsearch/data/snapshot"]
      cluster.routing.allocation.enable: "all"